language: python
python:
  - "2.6"
  - "2.7" 
  - "3.3"
  - "3.4" 
  - "3.5"
  - "3.6"
  - "3.6-dev"  
  - "3.7-dev"  
  - "nightly"

# matrix:
#   fast_finish: true

install:
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - if [[ "$WITH_OPENCL" == "1" ]]; then pip install --ignore-installed pyopencl; fi
  - python setup.py sdist
  - pip install -e .
  - export DISPLAY=:0.0
  # - python -c "import pyconrad.autoinit;pyconrad.edu().stanford.rsl.conrad.utils.Configuration.initConfig()"
# command to run tests
script:
  - python -c "import farneback3d"
  - pytest # or py.test for Python versions 3.5 and below

os:
  - linux
  # - osx

addons:
  apt:
    packages:
    - python-pycuda
    - python3-pycuda
