language: python
python:
  - "2.6"
  - "2.7" 
  - "3.3"
  - "3.4" 
  - "3.5"
  - "3.6"
  - "3.6-dev"  
  - "3.7-dev"  
  - "nightly"

# matrix:
#   fast_finish: true
env:
  - CUDA_VER=9.1
    

install:
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA_VER}_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1204_${CUDA_VER}_amd64.deb
  - CUDA_APT_VER=${CUDA_VER%-*}
  - CUDA_APT_VER=${CUDA_APT_VER/./-}
  - CUDA_PACKAGES="cuda-drivers cuda-core-${CUDA_APT_VER} cuda-cudart-dev-${CUDA_APT_VER} cuda-cufft-dev-${CUDA_APT_VER}"
  - echo "Installing ${CUDA_PACKAGES}"
  - sudo apt-get install -y ${CUDA_PACKAGES}
  - export CUDA_HOME=/usr/local/cuda-${CUDA_VER%%-*}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}
  - pip install -e .

script:
  - python -c "import farneback3d"
  - pytest # or py.test for Python versions 3.5 and below

os:
  - linux
  # - osx

# addons:
#   apt:
#     packages:
